# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb46356ce0a935fc6a77132b94bba0fc01889225c01128d6585dcdecfe29354524d747c7a74a87c0cbbea2dcafd69d016ba83d1e5581c19d7d8415d9654fb2a7

test:
  secret_key_base: a523f9936c650dcda2163bc32ff398ceccabf9ea3d01345eef8da978db05d5e5ef5a1a91010ca703c502b2228232fad8c448bb8d10087da274c830c4ba8d48d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
